# Introduction to NumPy

NumPy is a open source Python library used for working with arrays. NumPy stands for **Numerical Python**.</br>
It also has functions for working in domain of linear algebra, fourier transform, and matrices. </br>
NumPy was **created in 2005 by Travis Oliphant**. </br>
It is written partially in Python, but most of the parts that require fast computation are written in C or C++. </br>

* Github repository for NumPy source code is **https://github.com/numpy/numpy**


#### Why to use NumPy?
* We have lists in Python that serve the purpose of arrays, but they are slow to process. </br>
* NumPy aims to provide an array object that is up to *50x faster* than traditional Python lists. </br>
* NumPy arrays are stored at one continuous place in memory unlike python lists, so it can be accessed and manipulated very efficiently. This behavior is called **locality of reference** in computer science. Also it is optimized to work with latest CPU architectures.
* The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

#### Installation of NumPy
Prerequisist --- Python 3 and PIP

Execute below given command in command prompt for Windows users or in terminal for Linux users.

#### Importing NumPy 

In [1]:
import numpy    # or
import numpy as np  # or
from numpy import array, random, linspace 

### Array Dimensions (nested arrays)
*A dimension is a direction in which you can vary the specification of an array's elements.*

In [2]:
# 'ndim' function gives array dimensions 
a = np.array(42)                                                 # only one element = 0 dimension
b = np.array([1, 2, 3, 4, 5])                                    # One list (single '[]') = 1 dimension
c = np.array([[1, 2, 3], [4, 5, 6]])                             # Two lists inside '[]' = 2 dimension and so on
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  

e = np.array([1,2,3,4,5,6], ndmin=5)                # Specifying higher dimension by 'ndmin' while creating an array, here 5

print(a)
print("Dimension:",a.ndim)
print("\n",b)
print("Dimension:",b.ndim)
print("\n",c)
print("Dimension:",c.ndim)
print("\n",d)
print("Dimension:",d.ndim)
print("\n",e)
print("Dimension:", e.ndim)

42
Dimension: 0

 [1 2 3 4 5]
Dimension: 1

 [[1 2 3]
 [4 5 6]]
Dimension: 2

 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension: 3

 [[[[[1 2 3 4 5 6]]]]]
Dimension: 5


========================================================================================================================
### Datatypes in NumPy

Below are numpy datatypes and associated parameters to be passed to 'astype()' function for type casting or while creating an array.
* i - integer 
* b - boolean 
* u - unsigned integer 
* f - float 
* c - complex float 
* m - timedelta
* M - datetime
* O - object
* S - string 
* U - unicode string
* V - fixed chunk of memory for other type ( void )

**numpy_array.dtype** - gives datatype of numpy array </br>
**numpy_array.astype()** - to cast type of array 