#### Importing NumPy library

In [1]:
import numpy as np

# Numpy array creation 

## 1. numpy.array(): Conversion from Python objects (list, tuples, set, dict)

### i. Integer Array from python list

In [3]:
int_array = np.array([10,20,30,40,50,60,70])        # Declaring array using Numpy's array function
print(int_array)              
print("Array_datatype:", int_array.dtype)            # '.dtype' gives datatype info of array
print("Type of object:", type(int_array))
print("Array_itemsize:", int_array.dtype.itemsize)   # '.dtype.itemsize' gives size of an elements of an array. here int32 = 4 byte 
print("Array_size:", int_array.size)                 # '.size' gives size of an array i.e. total no. of elements present in array
print("Array_shape:", int_array.shape)

[10 20 30 40 50 60 70]
Array_datatype: int32
Type of object: <class 'numpy.ndarray'>
Array_itemsize: 4
Array_size: 7
Array_shape: (7,)


#### Two dimension array 

In [4]:
row1 = [10, 20, 30, 40]
row2 = [5, 15, 25, 35]
row3 = [50, 60, 70, 80]
two_dim_array = np.array([row1, row2, row3])
print(two_dim_array)
print("Array_datatype:",two_dim_array.dtype)
print("Array_itemsize:",two_dim_array.dtype.itemsize)
print("Array_size:",two_dim_array.size)
print("Array_shape:",two_dim_array.shape)

[[10 20 30 40]
 [ 5 15 25 35]
 [50 60 70 80]]
Array_datatype: int32
Array_itemsize: 4
Array_size: 12
Array_shape: (3, 4)


### ii. String Array from python list

In [5]:
str_array = np.array(["Red","Green","Orange"])
print(str_array)
print(str_array.dtype)
print(type(str_array))
print(str_array.dtype.itemsize)
print(str_array.size)

['Red' 'Green' 'Orange']
<U6
<class 'numpy.ndarray'>
24
3


* **Note:- "dtype.itemsize"** function gives total size (sum of all elements / characters) of max(item) in a list. </br>
> * E.g. - "np.array(["Red","Green","Orange"])", here max(item in a list) is "Orange" i.e. 6 characters. </br>
 1 character => '**<Unicode 1**' = 4 bytes. Hence "print(np.array(["Red","Green","Orange"]).dtype.itemsize)" = 4 x 6 = **24 bytes**. </br>
 Also, "print(np.array(["Red","Green","Orange"]).dtype)" = max(item in a list) i.e. "Orange" => 6 characters = '**<Unicode 6**'.

### iii. Decimal (float) Array from python list

In [6]:
row1 = [10.2, 20.3, 30.4, 40.5]
row2 = [5.1, 15.34, 25.34, 35.56]
row3 = [50.67, 60, 70.66, 80.9]
float_array = np.array([row1, row2, row3])
print(float_array)
print("Array_datatype:",float_array.dtype)
print("Array_itemsize:",float_array.dtype.itemsize)
print("Array_size:",float_array.size)
print("Array_shape:",float_array.shape)

[[10.2  20.3  30.4  40.5 ]
 [ 5.1  15.34 25.34 35.56]
 [50.67 60.   70.66 80.9 ]]
Array_datatype: float64
Array_itemsize: 8
Array_size: 12
Array_shape: (3, 4)


### iv. Date Array from python list

In [7]:
date_array = np.array(['2022-02-01', '2021-03-04', '1997-06-27'])
print(date_array)
print(date_array.dtype)
print(date_array.dtype.itemsize)    # Here '2021-03-04' = 10 characters => <Unicode 10, Hence size = 4 bytes * 10 = 40 bytes.
print(date_array.size)

['2022-02-01' '2021-03-04' '1997-06-27']
<U10
40
3


**Note: Here date array is treated as string. Hence 'dtype.itemsize' is 40**

In [8]:
extracted_month = date_array.astype("M")   # Here astype('M') specifies datetime array
print(extracted_month)
print(extracted_month.dtype)
print(extracted_month.dtype.itemsize)
print(extracted_month.size)

['2022-02-01' '2021-03-04' '1997-06-27']
datetime64[D]
8
3


**Note: Here we have specified datatype of an array as 'datetime' by 'astype('M')' method**

In [9]:
date_array = np.array(['2022-02-01', '2021-03-04', '1997-06-27'], dtype='M')
print(date_array)
print(date_array.dtype)
print(date_array.dtype.itemsize)

['2022-02-01' '2021-03-04' '1997-06-27']
datetime64[D]
8


### v. NumPy array from python tuple, set and dictionary

In [21]:
# Array from tuple()

tup = ((1,2,3,4,5), (6,7,8,9,10))
tup_array = np.array(tup)
print("tup -",type(tup))
print("tup_array -",type(tup_array))
print("Shape:",tup_array.shape)
print(tup_array)

print("Array indexing: tup_array[1][3] =",tup_array[1][3])

tup - <class 'tuple'>
tup_array - <class 'numpy.ndarray'>
Shape: (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array indexing: tup_array[1][3] = 9


In [17]:
# Array from set{}

set = {1,2,3,4,5,6,7,8}
set_array = np.array(set)
print("set -",type(set))
print("set_array -",type(set_array))
print("Shape:",set_array.shape)
print(set_array)

set - <class 'set'>
set_array - <class 'numpy.ndarray'>
Shape: ()
{1, 2, 3, 4, 5, 6, 7, 8}


In [18]:
# Array from dict{k:v}

dict = {1:'a', 2:'b', 3:'c'}
dict_array = np.array(dict)
print("dict -",type(dict))
print("dict_array -",type(dict_array))
print("Shape:",dict_array.shape)
print(dict_array)

dict - <class 'dict'>
dict_array - <class 'numpy.ndarray'>
Shape: ()
{1: 'a', 2: 'b', 3: 'c'}


**Note: Array indexing is not possible for those arrays which are created from unindexed / unordered python objects like set and dict. Numpy treat set and dict as a single element i.e. 0 dimensional array, hence giving index error.**

In [13]:
print("Array indexing: set_array[1][3] =",set_array[3])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [14]:
print("Array indexing: dict_array[1][3] =",dict_array[3])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed